name: Auto Streak
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update timestamp
        run: |
          echo "Automated streak update: $(date -u)" >> streak.txt
          git config --global user.name "Mohammad Zohaib"
          git config --global user.email "zohaib.tm2@gmail.com"
          git add streak.txt
          git commit -m "chore: automated daily streak update"
          git push
